// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckOutController from "./check_out_controller"
application.register("check-out", CheckOutController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalsController from "./modals_controller"
application.register("modals", ModalsController)
